const V=[
{name:"星乃ゆら",emoji:"🌸",subs:"428人",tag:"雑談・ゲーム",live:true},
{name:"月城ルナ",emoji:"🌙",subs:"812人",tag:"歌・ASMR",live:true},
{name:"猫宮こはく",emoji:"🐱",subs:"196人",tag:"ゲーム",live:false},
{name:"空色ミオ",emoji:"☁️",subs:"1,240人",tag:"歌・雑談",live:false}
];let page="home",balance=2840;const app=document.getElementById("app");
function topbar(back=false,title=""){return '<div class="top">'+(back?'<button class="back" onclick="go(\'home\')">‹</button>':'<div class="logo">VR</div>')+(title?'<b class="topTitle">'+title+'</b>':'')+'<div class="spacer"></div><button class="icon">⌕</button><button class="icon">♧</button><button class="icon">☺</button></div>'}
function nav(){return '<nav class="bottom">'+[["home","⌂","ホーム"],["live","▣","配信"],["discover","⌕","発掘"],["vr","♧","VR"],["mypage","♙","マイページ"]].map(x=>'<button class="nav '+(page===x[0]?'active':'')+'" onclick="go(\''+x[0]+'\')"><span>'+x[1]+'</span>'+x[2]+'</button>').join("")+'</nav>'}
function card(v,i){return '<article class="card" onclick="profile('+i+')"><div class="thumb">'+v.emoji+(v.live?'<b class="live">● LIVE</b>':'')+'</div><div class="card-body"><div class="name">'+v.name+'</div><div class="meta">登録者 '+v.subs+' ・ '+v.tag+'</div></div></article>'}
function quick(){return '<div class="quickCats"><button onclick="go(\'live\')"><span class="catIcon pink">▣</span><b>配信中</b></button><button onclick="go(\'discover\')"><span class="catIcon blue">★</span><b>新着</b></button><button onclick="go(\'discover\')"><span class="catIcon yellow">✦</span><b>おすすめ</b></button><button onclick="go(\'discover\')"><span class="catIcon cyan">♟</span><b>新人</b></button><button onclick="go(\'discover\')"><span class="catIcon orange">♛</span><b>ランキング</b></button></div>'}
function home(){return topbar()+'<section class="heroVisual" onclick="go(\'discover\')"><img src="assets/vr-hero.png" alt="VR公式キャラクター"><span class="prLabel">VR OFFICIAL</span></section>'+quick()+'<section class="section"><div class="section-head"><h2>配信中のVTuber</h2><button onclick="go(\'live\')">もっと見る ›</button></div><div class="cards">'+V.slice(0,2).map(card).join("")+'</div></section><section class="section"><div class="section-head"><h2>新人ピックアップ</h2><button onclick="go(\'discover\')">もっと見る ›</button></div><div class="discover" onclick="profile(2)"><div class="avatar">🐱</div><div><b>猫宮こはく</b><div class="meta">登録者196人 ・ ゲーム</div><p>まだ知らない推しに出会おう。</p></div></div></section><section class="section reward"><strong>ゲームを遊んで、推しを応援しよう！</strong><p>無料でVRを貯めて好きなVTuberへ。</p><button class="cta" onclick="go(\'vr\')">VRを貯める</button></section>'+nav()}
function discover(){return topbar(false)+'<h1>発掘</h1><div class="search">⌕ キーワードで検索（名前・ゲーム・タグ）</div><div class="chips"><button class="chip active">すべて</button><button class="chip">ゲーム</button><button class="chip">雑談</button><button class="chip">歌</button><button class="chip">新人</button></div><section class="section"><div class="section-head"><h2>注目の個人VTuber</h2></div><div class="cards">'+V.map(card).join("")+'</div></section>'+nav()}
function livePage(){return topbar(false)+'<h1>配信</h1><p class="sub">今この瞬間に配信しているVTuber</p><div class="cards">'+V.filter(v=>v.live).map((v,i)=>card(v,i)).join("")+'</div>'+nav()}
function vr(){return topbar(false)+'<h1>VRを貯める</h1><div class="wallet"><small>あなたの応援VR</small><b>'+balance.toLocaleString()+' VR</b><small>今月あなたが推しへ届けた応援</small><strong>♥ 6,320 VR</strong></div><div class="chips"><button class="chip active">すべて</button><button class="chip">アプリ</button><button class="chip">ゲーム</button><button class="chip">登録</button><button class="chip">動画視聴</button></div><div class="missions"><div class="mission" onclick="earn()">▶ <div><b>広告動画を視聴する</b><small>約30秒で完了</small></div><span class="pts">3 VR ›</span></div><div class="mission">▣ <div><b>アプリをインストール</b><small>ダウンロード後、起動で獲得</small></div><span class="pts">100 VR ›</span></div><div class="mission">🎮 <div><b>ゲームをプレイ</b><small>指定レベル到達で獲得</small></div><span class="pts">500 VR ›</span></div><div class="mission">♙ <div><b>無料会員登録</b><small>新規登録で獲得</small></div><span class="pts">300 VR ›</span></div></div>'+nav()}
function mypage(){return topbar(false)+'<h1>マイページ</h1><div class="myhead"><div class="avatar">👤</div><div><b>ゆう</b><div class="meta">@yuu_vr</div></div><button>プロフィールを編集</button></div><div class="wallet mini"><small>保有VR</small><b>'+balance.toLocaleString()+' VR</b><small>今月の応援額</small><strong>♥ 6,320 VR</strong></div><div class="menuList"><div>◎ 推し一覧 <span>›</span></div><div>▣ 応援履歴 <span>›</span></div><div>▤ 獲得履歴 <span>›</span></div><div>♡ お気に入り動画 <span>›</span></div><div>♧ お知らせ <span>›</span></div><div>⚙ 設定・ヘルプ <span>›</span></div></div>'+nav()}
function profile(i){page="profile";const v=V[i];app.innerHTML='<div class="shell">'+topbar(true)+'<div class="profile-cover">'+v.emoji+'</div><div class="profile"><div class="avatar">'+v.emoji+'</div><h1>'+v.name+' <span class="verified">✓</span></h1><div class="meta">'+v.tag+'</div><button class="follow" onclick="this.innerText=\'フォロー中 ✓\'">フォロー</button><div class="stats"><div><b>'+v.subs+'</b><br><small>登録者</small></div><div><b>3,560人</b><br><small>フォロワー</small></div><div><b>125,430 VR</b><br><small>応援総額</small></div></div><div class="tabs">ホーム　 動画　 ショート　 コミュニティ　 グッズ</div><div class="history"><b>🎖 あなたの応援歴</b><p>登録者312人の時から応援しています。</p><b class="grad">古参ランキング 上位8%</b></div><button class="cta wide" onclick="tip()">♥ このVTuberを応援する</button></div></div>'+nav()}
function tip(){let n=Number(prompt("応援するVR数","100"));if(n>0&&n<=balance){balance-=n;alert(n+" VRを送りました ♥");go("vr")}else if(n)alert("VR残高を確認してください")}
function earn(){balance+=3;alert("3 VR獲得しました！");go("vr")}
function go(p){page=p;let html=p==="discover"?discover():p==="live"?livePage():p==="vr"?vr():p==="mypage"?mypage():home();app.innerHTML='<div class="shell">'+html+'</div>';window.scrollTo(0,0)}go("home");