const V=[
{name:"天城リクト",channelId:"UCSMbl2XhcCjL-x_0yrrUU3g",emoji:"🐿️",subs:"2,550人",tag:"雑談・ゲーム・Shorts・Vlog",live:false,official:false,imagePolicy:"unknown",bio:"昼はシステムエンジニア、夜は個人勢VTuber。毎週土曜を中心に配信。",youtube:"https://www.youtube.com/@Amagi_Rikuto",site:"https://amagi-rikuto.com/",schedule:"毎週土曜 21:00",latest:"Shorts：毎週金曜17:00 / 通常動画：不定期"},
{name:"霧梨トセ",emoji:"🌌",subs:"公開情報",tag:"ゲーム・朗読",live:false,official:false,imagePolicy:"unknown",bio:"夢と現のあわいを歩く、おっとりマイペースな個人勢VTuber。ゲームや朗読を中心に活動。",site:"https://tosekirinashi.com/"},
{name:"雪明みてん",emoji:"🤍",subs:"914人",tag:"歌・雑談・ゲーム・参加型",live:false,official:false,imagePolicy:"restricted",bio:"北海道出身・在住の道産子白狐VTuber。歌枠、ホラー、RPG、雀魂などで活動。",youtube:"https://www.youtube.com/@Yume_miten",site:"https://yume-miten.jp/",channelId:"UCPMbyTlim27DvJtsa3kJHTQ",latest:"公式サイトに最新動画・Shorts一覧あり",featureVideo:"fZh2JNMH3_8"},
{name:"三毛猫わらび",channelId:"UC3bYL1a4b64ZYUy8Ow11H8g",emoji:"🐈",subs:"約4,410人",tag:"雑談・スプラ・ポケモン・MH",live:false,official:false,imagePolicy:"unknown",bio:"ネコ耳癒し系の個人勢VTuber。ゲーム配信や参加型配信を中心に活動。",youtube:"https://www.youtube.com/channel/UC3bYL1a4b64ZYUy8Ow11H8g"},
{name:"或灯あると",emoji:"👾",subs:"登録者少なめ",tag:"ゲーム・お絵描き・雑談",live:false,official:false,imagePolicy:"unknown",bio:"新人個人VTuber。まったりゲーム、お絵描き、雑談を中心に活動。",youtube:"https://www.youtube.com/@%E3%82%91%E5%8D%9C%E3%81%A1%E3%82%83%E3%82%93"}
];let page="home",balance=Number(localStorage.getItem("vrBalance")||2840),discoveryCandidates=[],discoverQuery="",discoverFilter="all";const followed=new Set(JSON.parse(localStorage.getItem("vrFollowed")||"[]"));const app=document.getElementById("app");
function topbar(back=false,title=""){return '<div class="top">'+(back?'<button class="back" onclick="go(\'home\')">‹</button>':'<div class="logo">VR</div>')+(title?'<b class="topTitle">'+title+'</b>':'')+'<div class="spacer"></div><button class="icon">⌕</button><button class="icon">♧</button><button class="icon">☺</button></div>'}
function nav(){return '<nav class="bottom">'+[["home","⌂","ホーム"],["live","▣","配信"],["shorts","▶","Shorts"],["discover","⌕","発掘"],["vr","♧","VR"],["mypage","♙","マイページ"]].map(x=>'<button class="nav '+(page===x[0]?'active':'')+'" onclick="go(\''+x[0]+'\')"><span>'+x[1]+'</span>'+x[2]+'</button>').join("")+'</nav>'}
function card(v,i){const ix=V.indexOf(v),pic=v.avatar?'<img src="'+esc(v.avatar)+'" alt="'+esc(v.name)+'">':v.emoji;return '<article class="card" onclick="profile('+ix+')"><div class="thumb">'+pic+(v.live?'<b class="live">● LIVE</b>':'')+'</div><div class="card-body"><div class="name">'+esc(v.name)+'</div><div class="meta">登録者 '+esc(v.subs)+' ・ '+esc(v.tag)+'</div></div></article>'}
function quick(){return '<div class="quickCats"><button onclick="go(\'live\')"><span class="catIcon pink">▣</span><b>配信中</b></button><button onclick="go(\'discover\')"><span class="catIcon blue">★</span><b>新着</b></button><button onclick="go(\'discover\')"><span class="catIcon yellow">✦</span><b>おすすめ</b></button><button onclick="go(\'discover\')"><span class="catIcon cyan">♟</span><b>新人</b></button><button onclick="go(\'discover\')"><span class="catIcon orange">♛</span><b>ランキング</b></button></div>'}
function home(){return topbar()+'<section class="heroVisual" onclick="go(\'discover\')"><img src="assets/vr-hero.png" alt="VR公式キャラクター"><span class="prLabel">VR OFFICIAL</span></section>'+quick()+'<section class="section"><div class="section-head"><h2>配信中のVTuber</h2><button onclick="go(\'live\')">もっと見る ›</button></div><div class="cards">'+V.filter(v=>v.live).slice(0,2).map(card).join("")+(V.some(v=>v.live)?'':'<div class="emptyCreator">現在確認できるライブ配信はありません</div>')+'</div></section><section class="shortPromo" onclick="go(\'shorts\')"><div><small>VR SHORTS</small><b>ショート動画から推しを発見</b><span>スワイプして見る →</span></div><strong>▶</strong></section><section class="section"><div class="section-head"><h2>新人ピックアップ</h2><button onclick="go(\'discover\')">もっと見る ›</button></div><div class="discover" onclick="profile(2)"><div class="avatar">'+(V[2].avatar?'<img src="'+esc(V[2].avatar)+'" alt="">':V[2].emoji)+'</div><div><b>'+esc(V[2].name)+'</b><div class="meta">登録者 '+esc(V[2].subs)+' ・ '+esc(V[2].tag)+'</div><p>まだ知らない推しに出会おう。</p></div></div></section><section class="section reward"><strong>ゲームを遊んで、推しを応援しよう！</strong><p>無料でVRを貯めて好きなVTuberへ。</p><button class="cta" onclick="go(\'vr\')">VRを貯める</button></section>'+nav()}
function candidateKey(v){return v.channelId||v.name}
function isFollowed(v){return followed.has(candidateKey(v))}
function toggleFollowCandidate(i){const v=discoveryCandidates[i],k=candidateKey(v);if(followed.has(k))followed.delete(k);else followed.add(k);localStorage.setItem("vrFollowed",JSON.stringify([...followed]));candidateProfile(i)}
const GENRES=["ゲーム","雑談","歌","ASMR","参加型","お絵描き","ホラー","FPS","RPG","麻雀"];
function creatorText(v){return ((v.name||"")+" "+(v.description||v.bio||"")+" "+(v.tag||"")+" "+(v.signals||[]).join(" ")).toLowerCase()}
function genresOf(v){const t=creatorText(v),rules={"ゲーム":["ゲーム","game","gaming"],"雑談":["雑談","chat","talk"],"歌":["歌","karaoke","sing"],"ASMR":["asmr"],"参加型":["参加型"],"お絵描き":["お絵描き","イラスト","drawing"],"ホラー":["ホラー","horror"],"FPS":["fps","valorant","apex"],"RPG":["rpg","ポケモン","ゼルダ"],"麻雀":["麻雀","雀魂"]};const a=GENRES.filter(g=>rules[g].some(k=>t.includes(k.toLowerCase())));return a.length?a:["その他"]}
function setDiscoverFilter(x){discoverFilter=x;go("discover")}
function setDiscoverQuery(x){discoverQuery=x;go("discover")}
function filteredCandidates(){return discoveryCandidates.filter(v=>{const t=((v.name||"")+" "+(v.description||"")+" "+(v.signals||[]).join(" ")).toLowerCase(),q=discoverQuery.trim().toLowerCase();if(q&&!t.includes(q))return false;if(discoverFilter==="new"&&Number(v.subs||999999)>1000)return false;if(discoverFilter==="pre"&&!/準備中|デビューする|初配信予定|再準備中/.test(t))return false;if(GENRES.includes(discoverFilter)&&!genresOf(v).includes(discoverFilter))return false;return true})}
function discoveryCard(v){const i=discoveryCandidates.indexOf(v),sub=v.subs==null?"非公開":Number(v.subs).toLocaleString()+"人",pre=/準備中|デビューする|初配信予定|再準備中/.test((v.name||"")+" "+(v.description||"")),desc=(v.description||"新人・個人VTuber候補").replace(/\s+/g," ").slice(0,76);return '<article class="discoverCandidate" onclick="candidateProfile('+i+')"><div class="discoverCandidateHead">'+(v.avatar?'<img src="'+esc(v.avatar)+'" alt="">':'<div class="avatar">V</div>')+'<div><span class="candidateBadge">'+(pre?'デビュー前':'発掘候補')+'</span><h3>'+esc(v.name)+'</h3><small>登録者 '+esc(sub)+'</small></div></div><p>'+esc(desc)+'</p><div class="candidateActions"><a href="'+esc(v.youtube)+'" target="_blank" rel="noopener" onclick="event.stopPropagation()">▶ YouTube</a><button onclick="event.stopPropagation();candidateProfile('+i+')">プロフィール</button></div></article>'}
function discover(){const xs=filteredCandidates();return topbar(false)+'<h1>発掘</h1><div class="searchBox">⌕ <input value="'+esc(discoverQuery)+'" oninput="setDiscoverQuery(this.value)" placeholder="名前・説明・タグで検索"></div><div class="chips"><button class="chip '+(discoverFilter==="all"?'active':'')+'" onclick="setDiscoverFilter(\'all\')">すべて</button><button class="chip '+(discoverFilter==="new"?'active':'')+'" onclick="setDiscoverFilter(\'new\')">登録者1,000人以下</button><button class="chip '+(discoverFilter==="pre"?'active':'')+'" onclick="setDiscoverFilter(\'pre\')">デビュー前</button></div><div class="genreChips"><button class="chip" onclick="setDiscoverFilter('ゲーム')">ゲーム</button><button class="chip" onclick="setDiscoverFilter('雑談')">雑談</button><button class="chip" onclick="setDiscoverFilter('歌')">歌</button><button class="chip" onclick="setDiscoverFilter('ASMR')">ASMR</button><button class="chip" onclick="setDiscoverFilter('参加型')">参加型</button><button class="chip" onclick="setDiscoverFilter('お絵描き')">お絵描き</button><button class="chip" onclick="setDiscoverFilter('ホラー')">ホラー</button><button class="chip" onclick="setDiscoverFilter('FPS')">FPS</button><button class="chip" onclick="setDiscoverFilter('RPG')">RPG</button><button class="chip" onclick="setDiscoverFilter('麻雀')">麻雀</button></div><section class="section"><div class="section-head"><h2>新しく見つけたVTuber</h2><span class="meta">'+xs.length+'人</span></div>'+(xs.length?'<div class="candidateList">'+xs.map(discoveryCard).join("")+'</div>':'<div class="emptyCreator">条件に合うVTuberはいません</div>')+'</section><section class="section"><div class="section-head"><h2>注目の個人VTuber</h2></div><div class="cards">'+V.map(card).join("")+'</div></section>'+nav()}
function candidateProfile(i){page="candidate";const v=discoveryCandidates[i];if(!v){go("discover");return}v.tag=genresOf(v).join("・");v.bio=v.description||"YouTubeで活動しているVTuber候補です。";v.emoji="V";v.official=false;const sub=v.subs==null?"非公開":Number(v.subs).toLocaleString()+"人",pre=/準備中|デビューする|初配信予定|再準備中/.test((v.name||"")+" "+(v.description||""));app.innerHTML='<div class="shell">'+topbar(true,"発掘プロフィール")+'<section class="candidateProfileHero">'+(v.avatar?'<img src="'+esc(v.avatar)+'" alt="">':'<div class="avatar">V</div>')+'<span class="candidateBadge">'+(pre?'デビュー前':'発掘候補')+'</span><h1>'+esc(v.name)+'</h1><p>登録者 '+esc(sub)+'</p><div class="creatorTags">'+genresOf(v).map(g=>"<span>"+esc(g)+"</span>").join("")+'</div></section><section class="creatorPanel"><h2>プロフィール</h2><p class="candidateLongBio">'+esc(v.description||"YouTubeで活動しているVTuber候補です。")+'</p></section><div class="candidateProfileActions"><button class="creatorFollow" onclick="toggleFollowCandidate('+i+')">'+(isFollowed(v)?'フォロー中 ✓':'フォロー')+'</button><a class="youtubePrimary" href="'+esc(v.youtube)+'" target="_blank" rel="noopener">▶ YouTubeを見る</a></div><button class="creatorSupport" onclick="alert(\'本人確認が完了するとVR応援を受け取れるようになります\')">♥ このVTuberを応援</button><section class="creatorPanel betaPanel"><h2>VRプロフィールについて</h2><p>このページはYouTubeの公開情報から自動作成された未認証プロフィールです。本人確認後に紹介文・画像・コミュニティ・グッズ・応援機能を管理できます。</p><button class="claimCandidate" onclick="go(\'claim\')">このVTuberは私です</button></section></div>'+nav()}
function claimPage(){return topbar(true,"本人確認")+'<section class="betaHero"><b>VTuber本人確認</b><p>β版では申請受付画面まで利用できます。本番ではYouTubeチャンネル所有確認と連携します。</p></section><div class="formCard"><label>YouTubeチャンネルURL<input placeholder="https://youtube.com/..."></label><label>連絡先メール<input type="email" placeholder="creator@example.com"></label><label>申請メモ<textarea placeholder="VRプロフィールの本人確認を申請します"></textarea></label><button class="cta" onclick="alert(\'β版のため送信はまだ行われません\')">確認申請へ</button></div>'+nav()}
function communityPage(){return topbar(false)+'<h1>コミュニティ</h1><section class="betaHero"><b>推しとファンが集まる場所</b><p>フォロー中VTuberのお知らせや投稿をまとめて表示する予定です。</p></section><div class="emptyCreator">コミュニティ投稿機能はバックエンド接続前です</div>'+nav()}
function goodsPage(){return topbar(false)+'<h1>グッズ</h1><section class="betaHero"><b>推しのグッズを見つけよう</b><p>本人確認済みVTuberの商品だけを掲載します。</p></section><div class="emptyCreator">ショップ連携は本番接続前です</div>'+nav()}

const DEMO_SHORTS=[{id:"UaU1iYdEGsw",name:"天ノ咲ねん"},{id:"Ol_6WuzjT0o",name:"VTuber Shorts"}];
function shortFeed(){const real=[];V.forEach(v=>(v.shorts||[]).forEach(s=>real.push({id:s.id,name:v.name,publishedAt:s.publishedAt||""})));real.sort((a,b)=>String(b.publishedAt).localeCompare(String(a.publishedAt)));return real.length?real:DEMO_SHORTS}
let shortSoundOn=false,shortObserver=null;
function shortsPage(){return '<div class="shortsFull"><div class="shortSound" onclick="enableShortSound()">🔊 音声をON</div><div class="shortTop"><button onclick="go(\'home\')">‹</button><b>Shorts</b><span>VR</span></div>'+shortFeed().map((v,i)=>'<section class="shortItem ytShort" data-id="'+v.id+'"><iframe class="ytFrame" title="'+v.name+'" allow="autoplay; encrypted-media; picture-in-picture" allowfullscreen></iframe><div class="shortInfo"><b>'+v.name+'</b><p>YouTube Shorts</p></div></section>').join('')+'</div>'}
function shortUrl(id){return 'https://www.youtube.com/embed/'+id+'?enablejsapi=1&autoplay=1&mute='+(shortSoundOn?0:1)+'&playsinline=1&loop=1&playlist='+id+'&rel=0'}
function activateShort(el){document.querySelectorAll('.ytShort').forEach(x=>{const f=x.querySelector('.ytFrame');if(x===el){const u=shortUrl(x.dataset.id);if(f.getAttribute('src')!==u)f.setAttribute('src',u)}else{f.removeAttribute('src')}})}
function initShortObserver(){const feed=document.querySelector('.shortsFull'),items=[...document.querySelectorAll('.ytShort')];if(!feed||!items.length)return;if(shortObserver)shortObserver.disconnect();shortObserver=new IntersectionObserver(es=>{let best=null;es.forEach(e=>{if(e.isIntersecting&&(!best||e.intersectionRatio>best.intersectionRatio))best=e});if(best&&best.intersectionRatio>.55)activateShort(best.target)},{root:feed,threshold:[.55,.75,.95]});items.forEach(x=>shortObserver.observe(x));activateShort(items[0])}
function enableShortSound(){shortSoundOn=true;const items=[...document.querySelectorAll('.ytShort')],feed=document.querySelector('.shortsFull');let active=items[0],best=Infinity;items.forEach(x=>{const d=Math.abs(x.getBoundingClientRect().top-(feed?feed.getBoundingClientRect().top:0));if(d<best){best=d;active=x}});activateShort(active);const b=document.querySelector('.shortSound');if(b){b.textContent='🔊 音声ON';b.classList.add('on')}}
function livePage(){const xs=V.filter(v=>v.live),up=V.flatMap(v=>(v.upcoming||[]).map(x=>({v,x}))).sort((a,b)=>String(a.x.scheduledStartTime||"").localeCompare(String(b.x.scheduledStartTime||"")));return topbar(false)+'<h1>配信</h1><p class="sub">今この瞬間に配信しているVTuber</p><div class="cards">'+xs.map(card).join("")+(xs.length?'':'<div class="emptyCreator">現在確認できるライブ配信はありません</div>')+'</div><section class="section"><div class="section-head"><h2>配信予定</h2></div>'+ (up.length?'<div class="missions">'+up.slice(0,8).map(o=>'<a class="mission" href="https://www.youtube.com/watch?v='+encodeURIComponent(o.x.id)+'" target="_blank" rel="noopener"><div><b>'+esc(o.v.name)+'</b><small>'+esc(o.x.title||"配信予定")+'<br>'+formatJst(o.x.scheduledStartTime)+'</small></div><span>▶</span></a>').join("")+'</div>':'<div class="emptyCreator">現在確認できる配信予定はありません</div>')+'</section>'+nav()}
function vr(){return topbar(false)+'<h1>VRを貯める</h1><div class="wallet"><small>あなたの応援VR</small><b>'+balance.toLocaleString()+' VR</b><small>今月あなたが推しへ届けた応援</small><strong>♥ 6,320 VR</strong></div><div class="chips"><button class="chip active">すべて</button><button class="chip">アプリ</button><button class="chip">ゲーム</button><button class="chip">登録</button><button class="chip">動画視聴</button></div><div class="missions"><div class="mission" onclick="earn()">▶ <div><b>広告動画を視聴する</b><small>約30秒で完了</small></div><span class="pts">3 VR ›</span></div><div class="mission">▣ <div><b>アプリをインストール</b><small>ダウンロード後、起動で獲得</small></div><span class="pts">100 VR ›</span></div><div class="mission">🎮 <div><b>ゲームをプレイ</b><small>指定レベル到達で獲得</small></div><span class="pts">500 VR ›</span></div><div class="mission">♙ <div><b>無料会員登録</b><small>新規登録で獲得</small></div><span class="pts">300 VR ›</span></div></div>'+nav()}
function mypage(){return topbar(false)+'<h1>マイページ</h1><div class="myhead"><div class="avatar">👤</div><div><b>ゆう</b><div class="meta">@yuu_vr</div></div><button>プロフィールを編集</button></div><div class="wallet mini"><small>保有VR</small><b>'+balance.toLocaleString()+' VR</b><small>今月の応援額</small><strong>♥ 6,320 VR</strong></div><div class="menuList"><div>◎ 推し一覧 <span>›</span></div><div>▣ 応援履歴 <span>›</span></div><div>▤ 獲得履歴 <span>›</span></div><div>♡ お気に入り動画 <span>›</span></div><div>♧ お知らせ <span>›</span></div><div>⚙ 設定・ヘルプ <span>›</span></div></div>'+nav()}
function esc(s){return String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]))}
function formatJst(s){if(!s)return "日時未定";try{return new Intl.DateTimeFormat("ja-JP",{timeZone:"Asia/Tokyo",month:"numeric",day:"numeric",weekday:"short",hour:"2-digit",minute:"2-digit"}).format(new Date(s))}catch(e){return s}}
function videoCards(v){const items=(v.videos||[]).slice(0,4);if(!items.length&&v.featureVideo)items.push({id:v.featureVideo,title:"YouTube動画",thumbnail:"https://i.ytimg.com/vi/"+v.featureVideo+"/hqdefault.jpg"});if(!items.length)return '<div class="emptyCreator">最新動画はYouTubeで確認できます</div>';return '<div class="creatorVideoGrid">'+items.map(x=>'<a href="https://www.youtube.com/watch?v='+encodeURIComponent(x.id)+'" target="_blank" rel="noopener"><img src="'+esc(x.thumbnail||("https://i.ytimg.com/vi/"+x.id+"/hqdefault.jpg"))+'" alt=""><b>'+esc(x.title||"動画")+'</b></a>').join("")+'</div>'}
function profile(i){
 page="profile";const v=V[i];if(!v){go("discover");return}
 const avatar=v.avatar?'<img src="'+esc(v.avatar)+'" alt="'+esc(v.name)+'">':'<span>'+v.emoji+'</span>';
 const coverStyle=v.cover?' style="background-image:url(\''+esc(v.cover)+'\')"':'';
 const links=(v.youtube?'<a href="'+esc(v.youtube)+'" target="_blank" rel="noopener">▶ YouTube ↗</a>':'')+(v.x?'<a href="'+esc(v.x)+'" target="_blank" rel="noopener">𝕏 X ↗</a>':'')+(v.site?'<a href="'+esc(v.site)+'" target="_blank" rel="noopener">🔗 公式サイト ↗</a>':'');
 const tags=String(v.tag||"").split("・").filter(Boolean).map(x=>'<span>'+esc(x)+'</span>').join("");
 app.innerHTML='<div class="creatorPage"><header class="creatorTop"><button onclick="go(\'discover\')">‹</button><div></div><button>↗</button><button>•••</button></header><section class="creatorHero"'+coverStyle+'><div class="creatorHeroFallback">'+(v.cover?'':v.emoji)+'</div></section><main class="creatorMain"><div class="creatorIdentity"><div class="creatorAvatar2">'+avatar+'</div><div class="creatorTitle"><span class="unverified">'+(v.official?'認証済み':'未認証')+'</span><h1>'+esc(v.name)+'</h1><small>'+(v.handle?esc(v.handle):'個人VTuber')+'</small></div><button class="creatorFollow" onclick="this.textContent=\'フォロー中 ✓\'">フォロー</button></div><p class="creatorBio">'+esc(v.bio||"")+'</p><div class="creatorTags">'+tags+'</div><div class="creatorLinks">'+links+'</div><section class="creatorStats"><div><b>'+esc(v.subs||"—")+'</b><span>YouTube登録者</span></div><div><b>'+(v.official?'認証済み':'未認証')+'</b><span>VR状態</span></div><div><b>—</b><span>応援総額</span></div></section><nav class="creatorTabs"><b>ホーム</b><span>動画</span><span>Shorts</span><span>コミュニティ</span><span>グッズ</span></nav><button class="creatorSupport" onclick="alert(\''+(v.official?'応援機能は準備中です':'本人確認後に利用できます')+'\')">♥ このVTuberを応援する</button><section class="creatorPanel"><div class="creatorPanelHead"><h2>📅 配信予定</h2><span>もっと見る ›</span></div><p>'+(v.upcoming&&v.upcoming.length?'<a href="https://www.youtube.com/watch?v='+encodeURIComponent(v.upcoming[0].id)+'" target="_blank" rel="noopener"><b>'+esc(v.upcoming[0].title)+'</b><br>'+formatJst(v.upcoming[0].scheduledStartTime)+' ▶ YouTube</a>':(v.schedule?esc(v.schedule):'次回の配信予定は未登録です'))+'</p></section><section class="creatorPanel"><div class="creatorPanelHead"><h2>▶ 最新の動画</h2><a href="'+esc(v.youtube||"#")+'" target="_blank" rel="noopener">もっと見る ›</a></div>'+videoCards(v)+'</section><p class="claimNote">このページは公開情報をもとにした未認証プロフィールです。本人確認後、VTuber本人がトップ画像・アイコン・紹介文などを管理できます。</p></main></div>'+nav()
}
function tip(){let n=Number(prompt("応援するVR数","100"));if(n>0&&n<=balance){balance-=n;alert(n+" VRを送りました ♥");go("vr")}else if(n)alert("VR残高を確認してください")}
function earn(){balance+=3;localStorage.setItem("vrBalance",balance);alert("3 VR獲得しました！");go("vr")}
async function loadYouTubeData(){try{const r=await fetch("./data/youtube.json?v="+Date.now(),{cache:"no-store"});if(!r.ok)return;const d=await r.json();(d.creators||[]).forEach(y=>{const v=V.find(x=>(y.channelId&&x.channelId===y.channelId)||x.name===y.name);if(v){const {name,...rest}=y;Object.assign(v,rest)}});}catch(e){console.warn("YouTube data unavailable",e)}}
async function loadDiscoveryData(){try{const r=await fetch("./data/discovery-candidates.json?v="+Date.now(),{cache:"no-store"});if(!r.ok)return;const d=await r.json();discoveryCandidates=(d.candidates||[]).filter(x=>!/切り抜きch|切り抜きチャンネル|まとめch|まとめチャンネル/i.test((x.name||"")+" "+(x.description||"")));if(page==="discover")go("discover")}catch(e){console.warn("Discovery data unavailable",e)}}
function go(p){page=p;let html=p==="discover"?discover():p==="live"?livePage():p==="vr"?vr():p==="mypage"?mypage():p==="shorts"?shortsPage():p==="claim"?claimPage():p==="community"?communityPage():p==="goods"?goodsPage():home();app.innerHTML='<div class="shell">'+html+'</div>';if(p==="shorts")setTimeout(initShortObserver,0);window.scrollTo(0,0)}go("home");loadYouTubeData().then(()=>{if(page==="home")go("home")});loadDiscoveryData();
